//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFWebService.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO {
            get {
                return this.FIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FIOField, value) != true)) {
                    this.FIOField = value;
                    this.RaisePropertyChanged("FIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        void AddDict(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        System.Threading.Tasks.Task AddDictAsync(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        void UpdDict(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        System.Threading.Tasks.Task UpdDictAsync(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        void DelDict(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        System.Threading.Tasks.Task DelDictAsync(WFWebService.WS.Phone phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDict", ReplyAction="http://tempuri.org/IService1/GetDictResponse")]
        WFWebService.WS.Phone[] GetDict();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDict", ReplyAction="http://tempuri.org/IService1/GetDictResponse")]
        System.Threading.Tasks.Task<WFWebService.WS.Phone[]> GetDictAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WFWebService.WS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WFWebService.WS.IService1>, WFWebService.WS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddDict(WFWebService.WS.Phone phone) {
            base.Channel.AddDict(phone);
        }
        
        public System.Threading.Tasks.Task AddDictAsync(WFWebService.WS.Phone phone) {
            return base.Channel.AddDictAsync(phone);
        }
        
        public void UpdDict(WFWebService.WS.Phone phone) {
            base.Channel.UpdDict(phone);
        }
        
        public System.Threading.Tasks.Task UpdDictAsync(WFWebService.WS.Phone phone) {
            return base.Channel.UpdDictAsync(phone);
        }
        
        public void DelDict(WFWebService.WS.Phone phone) {
            base.Channel.DelDict(phone);
        }
        
        public System.Threading.Tasks.Task DelDictAsync(WFWebService.WS.Phone phone) {
            return base.Channel.DelDictAsync(phone);
        }
        
        public WFWebService.WS.Phone[] GetDict() {
            return base.Channel.GetDict();
        }
        
        public System.Threading.Tasks.Task<WFWebService.WS.Phone[]> GetDictAsync() {
            return base.Channel.GetDictAsync();
        }
    }
}
